### PR TITLE
Add Route53

### PR DESCRIPTION
**Pull request by micahwedemeyer**
I hope I did this right. I ran it against the Go SDK and it generated a file. I eyeballed the file and it looked like code to me...

Is there anything else I can do to help?

### CODE REVIEW

**Comment by jkakar** [comment]
Thanks for the pull request @micahwedemeyer!  Unfortunately, this won't work because the Route53 API uses the `rest-xml` protocol which isn't yet supported by the code generator.  Each of the JSON descriptions for the various APIs defines the service's protocol, for example:

  https://github.com/aws/aws-sdk-go/blob/master/models/apis/route53/2013-04-01/api-2.json#L7

**Comment by jkakar** [comment]
What I expect will happen when you attempt to use the client you generated is that (a) the URLs won't work right and you'll get a bunch of 404's and (b) even if you do manage to make a request processing will fail when the client tries to parse XML as JSON. :/

**Comment by micahwedemeyer** [comment]
Yeah, messing with it now and I can't get things to work right. Of course, I'm very new to Elixir (been a Rubyist for many years), so that's not helping either.

Thanks for looking! If I have any success, I'll let you know.

**Comment by jkakar** [comment]
Yeah, the problem we need to solve is writing a function that can turn generic XML returned by an AWS service into an Elixir map and vice versa.  At that point, we can refactor the existing `rest-json` code generator to handle XML instead of JSON.  I haven't made time to look at how to handle the transformation of XML to Elixir map and vice versa yet, so I don't really know how easy or hard it is.

Anyway, thanks for taking the time to dig in.  If you have questions, or want to get involved somehow, please let me know.  I'm happy to help where I can.

**Pull request closed without merging**
